services:
  postgres:
    image: postgres:16
    env_file: .env.postgres
    networks:
      - app-network
    expose:
      - "5432"
    healthcheck:
      test: ["CMD-SHELL", "pg_isready -U $${POSTGRES_USER} -d $${POSTGRES_DB}"]
      interval: 5s
      timeout: 3s
      retries: 5
    volumes:
      - ./postgres/initdb:/docker-entrypoint-initdb.d

  minio:
    image: minio/minio
    command: server /data
    env_file: .env.minio
    networks:
      - app-network
    expose:
      - "9000"
    healthcheck:
      test: ["CMD", "curl", "-f", "http://localhost:9000/minio/health/live"]
      interval: 5s
      timeout: 3s
      retries: 5

  minio-init:
    image: minio/mc
    entrypoint: /init-minio.sh
    env_file: .env.minio-init
    networks:
      - app-network
    depends_on:
      minio:
        condition: service_healthy   
    volumes:
      - /opt/test-data:/test-data
      - ./minio/init-minio.sh:/init-minio.sh

  backend:
    image: ${DOCKERHUB_USERNAME}/${BACKEND_IMAGE}
    env_file: .env.backend
    networks:
      - app-network
    depends_on:
      postgres:
        condition: service_healthy
      minio-init:
        condition: service_completed_successfully
    expose:
      - "8080"
    healthcheck:
      test: ["CMD", "curl", "-f", "http://localhost:8081/actuator/health"]
      interval: 5s
      timeout: 3s
      retries: 10

  nginx:
    image: nginx:alpine
    ports:
      - "8080:8080"
    networks:
      - app-network
    depends_on:
      backend:
        condition: service_healthy
    volumes:
      - ./nginx/nginx.conf:/etc/nginx/conf.d/default.conf

networks:
  app-network:
    driver: bridge